---
- name: Check backup/boot exists
  stat:
    path: /root/backup/boot
  register: stat_result

- name: Check lvm snap exists
  command: lvdisplay 'ubuntu-vg/snap'
  no_log: True
  changed_when: False
  register: lvdisplay
  failed_when: lvdisplay.rc != 0

- name: merge snapshot into lv
  command: lvconvert --merge /dev/ubuntu-vg/snap
  when: lvdisplay.rc == 0
  register: merge

- name: mapping lv value to pv value
  command: lvs -ao +devices
  when: lvdisplay.rc == 0
  register: map

- name: removing boot
  command: /bin/rm -rf /boot/*
  args:
    warn: false

- name: restore boot
  synchronize:
    src: /root/backup/boot/
    dest: /boot/
    delete: yes
    recursive: yes
  delegate_to: "{{ inventory_hostname }}" 

#- name: Check absence of snapshot
#  command: lvdisplay 'ubuntu-vg/snap'
#  changed_when: False
#  register: lvdisplay
#  failed_when: lvdisplay.rc == 0
#  retries: 10
#  delay: 30

- name: mapping lv value to pv value
  command: update-grub

#- name: Reboot for lvs to rollback
#  reboot:
#    msg: "Reboot initiated by Ansible for lvm snapshot rollback"
#    connect_timeout: 5
#    reboot_timeout: 300
#    pre_reboot_delay: 0
#    post_reboot_delay: 30
#    test_command: uptime
#  when: merge.rc == 0 and map.rc == 0
...