---
- name: physical LVM snapshot for RHEL
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: physical LVM snapshot for Debian
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'
...